project_id = "btteqktyhnyeycmognox"

[functions.extract-bet-from-image]
verify_jwt = true

[functions.get-betting-odds]
verify_jwt = false

[functions.generate-feed]
verify_jwt = true

[functions.scrape-sports-news]
verify_jwt = true

[functions.scrape-celebrity-picks]
verify_jwt = true
