-- Add additional sports betting influencers and personalities to public_bettors table
INSERT INTO public.public_bettors (username, display_name, bio, is_verified, social_handles, source_urls) VALUES
('mrbankstips', 'Mr. Banks', 'Professional sports betting tipster and handicapper', true, '{"twitter": "mrbankstips"}', ARRAY['https://twitter.com/mrbankstips']),
('mrbayoa1', 'Mr. Bayo', 'Sports betting analyst and content creator', true, '{"twitter": "mrbayoa1"}', ARRAY['https://twitter.com/mrbayoa1']),
('MatthewBerryTMR', 'Matthew Berry', 'Fantasy football expert and sports analyst', true, '{"twitter": "MatthewBerryTMR"}', ARRAY['https://twitter.com/MatthewBerryTMR']),
('jasonlacanfora', 'Jason La Canfora', 'NFL insider and sports betting analyst', true, '{"twitter": "jasonlacanfora"}', ARRAY['https://twitter.com/jasonlacanfora']),
('dangambleai', 'Dan', 'AI-powered sports betting insights and analytics', true, '{"twitter": "dangambleai"}', ARRAY['https://twitter.com/dangambleai']),
('jasonffl', 'Jason Moore', 'Fantasy football expert and sports betting analyst', true, '{"twitter": "jasonffl"}', ARRAY['https://twitter.com/jasonffl']),
('timmyofdelta', 'Timmy Lewis', 'Sports betting content creator', true, '{"twitter": "timmyofdelta"}', ARRAY['https://twitter.com/timmyofdelta']),
('tmathsports', 'Taylor Mathis', 'Sports betting host and content creator', true, '{"twitter": "tmathsports"}', ARRAY['https://twitter.com/tmathsports']),
('SalVetriDFS', 'Sal Vetri', 'DFS and sports betting expert', true, '{"twitter": "SalVetriDFS"}', ARRAY['https://twitter.com/SalVetriDFS']),
('JimmySportPicks', 'Jimmy', 'Professional sports handicapper', true, '{"twitter": "JimmySportPicks"}', ARRAY['https://twitter.com/JimmySportPicks']),
('AlexMonahan', 'Alex Monahan', 'Fantasy sports and betting analyst', true, '{"twitter": "AlexMonahan"}', ARRAY['https://twitter.com/AlexMonahan']),
('JohnHyslop', 'John Hyslop', 'Sports betting and fantasy expert', true, '{"twitter": "JohnHyslop"}', ARRAY['https://twitter.com/JohnHyslop']),
('Lauren_Cowling', 'Lauren Cowling', 'Sports betting analyst and content creator', true, '{"twitter": "Lauren_Cowling"}', ARRAY['https://twitter.com/Lauren_Cowling']),
('JeffRatcliffe', 'Jeff Ratcliffe', 'Fantasy football and NFL betting analyst', true, '{"twitter": "JeffRatcliffe"}', ARRAY['https://twitter.com/JeffRatcliffe']),
('MattDowns', 'Matt Downs', 'Sports betting expert and analyst', true, '{"twitter": "MattDowns"}', ARRAY['https://twitter.com/MattDowns']),
('ThePME', 'Pat Mayo', 'DFS expert and sports betting analyst', true, '{"twitter": "ThePME"}', ARRAY['https://twitter.com/ThePME']),
('ArielEpstein', 'Ariel Epstein', 'Sports betting analyst and content creator', true, '{"twitter": "ArielEpstein"}', ARRAY['https://twitter.com/ArielEpstein']),
('GUnit_81', 'Greg Peterson', 'Sports betting analyst and handicapper', true, '{"twitter": "GUnit_81"}', ARRAY['https://twitter.com/GUnit_81']),
('BradPowers7', 'Brad Powers', 'Sports betting expert and tipster', true, '{"twitter": "BradPowers7"}', ARRAY['https://twitter.com/BradPowers7']),
('AidenChaggie', 'Aiden Chaggie', 'Sports betting content creator', true, '{"twitter": "AidenChaggie"}', ARRAY['https://twitter.com/AidenChaggie']),
('LizLoza_FS', 'Liz Loza', 'Fantasy sports and betting analyst', true, '{"twitter": "LizLoza_FS"}', ARRAY['https://twitter.com/LizLoza_FS']),
('PamelaM35', 'Pamela Maldonado', 'Sports betting analyst', true, '{"twitter": "PamelaM35"}', ARRAY['https://twitter.com/PamelaM35']),
('spanky', 'Gadoon Kyrollos', 'Sports betting and fantasy expert', true, '{"twitter": "spanky"}', ARRAY['https://twitter.com/spanky']),
('FezzikSports', 'Steve Fezzik', 'Professional sports bettor and handicapper', true, '{"twitter": "FezzikSports"}', ARRAY['https://twitter.com/FezzikSports']),
('YoucapperSports', 'Ronald Cabang', 'Professional sports handicapper', true, '{"twitter": "YoucapperSports"}', ARRAY['https://twitter.com/YoucapperSports']),
('TokyoBrandon', 'Tokyo Brandon', 'Sports betting analyst and content creator', true, '{"twitter": "TokyoBrandon"}', ARRAY['https://twitter.com/TokyoBrandon']),
('Datsq9', 'Datsq9', 'Sports betting tipster and analyst', true, '{"twitter": "Datsq9"}', ARRAY['https://twitter.com/Datsq9']),
('DevinsBookie', 'Devin''s Bookie', 'Sports betting content and picks', true, '{"twitter": "DevinsBookie"}', ARRAY['https://twitter.com/DevinsBookie']),
('PropBomb', 'PropBomb', 'Prop bet specialist and analyst', true, '{"twitter": "PropBomb"}', ARRAY['https://twitter.com/PropBomb']),
('PropBetGuy', 'Prop Bet Guy', 'Prop betting expert and content creator', true, '{"twitter": "PropBetGuy"}', ARRAY['https://twitter.com/PropBetGuy']),
('HammeringHank', 'Hammering Hank', 'Sports betting handicapper', true, '{"twitter": "HammeringHank"}', ARRAY['https://twitter.com/HammeringHank']),
('DeadPrezPicks', 'Dead President Picks', 'Sports betting picks and analysis', true, '{"twitter": "DeadPrezPicks"}', ARRAY['https://twitter.com/DeadPrezPicks']),
('TheSharpPlays', 'TheSharpPlays', 'Sharp betting analysis and picks', true, '{"twitter": "TheSharpPlays"}', ARRAY['https://twitter.com/TheSharpPlays']),
('ShannonSharpe', 'Shannon Sharpe', 'NFL legend and sports media personality', true, '{"twitter": "ShannonSharpe"}', ARRAY['https://twitter.com/ShannonSharpe']),
('RealSkipBayless', 'Skip Bayless', 'Sports media personality and analyst', true, '{"twitter": "RealSkipBayless"}', ARRAY['https://twitter.com/RealSkipBayless']),
('stephenasmith', 'Stephen A. Smith', 'ESPN personality and sports analyst', true, '{"twitter": "stephenasmith"}', ARRAY['https://twitter.com/stephenasmith']),
('ClayTravis', 'Clay Travis', 'OutKick founder and sports betting analyst', true, '{"twitter": "ClayTravis"}', ARRAY['https://twitter.com/ClayTravis']),
('LeBatardShow', 'Dan Le Batard', 'Sports media personality and show host', true, '{"twitter": "LeBatardShow"}', ARRAY['https://twitter.com/LeBatardShow']),
('richeisen', 'Rich Eisen', 'NFL Network host and sports broadcaster', true, '{"twitter": "richeisen"}', ARRAY['https://twitter.com/richeisen']),
('notthefakeSVP', 'Scott Van Pelt', 'ESPN host and sports betting analyst', true, '{"twitter": "notthefakeSVP"}', ARRAY['https://twitter.com/notthefakeSVP']),
('Espngreeny', 'Mike Greenberg', 'ESPN host and sports personality', true, '{"twitter": "Espngreeny"}', ARRAY['https://twitter.com/Espngreeny']),
('chrisfallica', 'Chris "The Bear" Fallica', 'FOX Sports betting analyst', true, '{"twitter": "chrisfallica"}', ARRAY['https://twitter.com/chrisfallica']),
('NoisyHuevos', 'Brad Evans', 'Fantasy football and betting expert', true, '{"twitter": "NoisyHuevos"}', ARRAY['https://twitter.com/NoisyHuevos']),
('MattMoneySmith', 'Matt "Money" Smith', 'Sports betting personality and analyst', true, '{"twitter": "MattMoneySmith"}', ARRAY['https://twitter.com/MattMoneySmith']),
('mlombardiNFL', 'Mike Lombardi', 'NFL analyst and former executive', true, '{"twitter": "mlombardiNFL"}', ARRAY['https://twitter.com/mlombardiNFL']),
('ryenarussillo', 'Ryen Russillo', 'Sports podcaster and betting analyst', true, '{"twitter": "ryenarussillo"}', ARRAY['https://twitter.com/ryenarussillo']),
('MadDogUnleashed', 'Chris "Mad Dog" Russo', 'Sports radio legend and analyst', true, '{"twitter": "MadDogUnleashed"}', ARRAY['https://twitter.com/MadDogUnleashed']),
('dpshow', 'Dan Patrick', 'Sports broadcaster and show host', true, '{"twitter": "dpshow"}', ARRAY['https://twitter.com/dpshow'])
ON CONFLICT (username) DO NOTHING;