-- Delete existing NCAAMB teams to replace with full roster
DELETE FROM public.teams WHERE league = 'NCAAMB';

-- Add all NCAA Men's Basketball teams matching football teams
INSERT INTO public.teams (id, name, mascot, league, sport, logo_url) VALUES
('ncaamb_alabama', 'Alabama', 'Crimson Tide', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png'),
('ncaamb_arizona', 'Arizona', 'Wildcats', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png'),
('ncaamb_arizona_state', 'Arizona State', 'Sun Devils', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/9.png'),
('ncaamb_arkansas', 'Arkansas', 'Razorbacks', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png'),
('ncaamb_auburn', 'Auburn', 'Tigers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2.png'),
('ncaamb_baylor', 'Baylor', 'Bears', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/239.png'),
('ncaamb_boston_college', 'Boston College', 'Eagles', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/103.png'),
('ncaamb_byu', 'BYU', 'Cougars', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/252.png'),
('ncaamb_california', 'California', 'Golden Bears', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/25.png'),
('ncaamb_cincinnati', 'Cincinnati', 'Bearcats', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png'),
('ncaamb_clemson', 'Clemson', 'Tigers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/228.png'),
('ncaamb_colorado', 'Colorado', 'Buffaloes', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/38.png'),
('ncaamb_duke', 'Duke', 'Blue Devils', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png'),
('ncaamb_florida', 'Florida', 'Gators', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png'),
('ncaamb_florida_state', 'Florida State', 'Seminoles', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/52.png'),
('ncaamb_georgia', 'Georgia', 'Bulldogs', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/61.png'),
('ncaamb_georgia_tech', 'Georgia Tech', 'Yellow Jackets', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/59.png'),
('ncaamb_houston', 'Houston', 'Cougars', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png'),
('ncaamb_illinois', 'Illinois', 'Fighting Illini', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/356.png'),
('ncaamb_indiana', 'Indiana', 'Hoosiers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/84.png'),
('ncaamb_iowa', 'Iowa', 'Hawkeyes', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2294.png'),
('ncaamb_iowa_state', 'Iowa State', 'Cyclones', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png'),
('ncaamb_kansas', 'Kansas', 'Jayhawks', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png'),
('ncaamb_kansas_state', 'Kansas State', 'Wildcats', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2306.png'),
('ncaamb_kentucky', 'Kentucky', 'Wildcats', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/96.png'),
('ncaamb_louisville', 'Louisville', 'Cardinals', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/97.png'),
('ncaamb_lsu', 'LSU', 'Tigers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/99.png'),
('ncaamb_maryland', 'Maryland', 'Terrapins', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/120.png'),
('ncaamb_miami', 'Miami', 'Hurricanes', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png'),
('ncaamb_michigan', 'Michigan', 'Wolverines', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png'),
('ncaamb_michigan_state', 'Michigan State', 'Spartans', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/127.png'),
('ncaamb_minnesota', 'Minnesota', 'Golden Gophers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/135.png'),
('ncaamb_mississippi_state', 'Mississippi State', 'Bulldogs', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/344.png'),
('ncaamb_missouri', 'Missouri', 'Tigers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/142.png'),
('ncaamb_nc_state', 'NC State', 'Wolfpack', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/152.png'),
('ncaamb_nebraska', 'Nebraska', 'Cornhuskers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/158.png'),
('ncaamb_north_carolina', 'North Carolina', 'Tar Heels', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png'),
('ncaamb_northwestern', 'Northwestern', 'Wildcats', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/77.png'),
('ncaamb_notre_dame', 'Notre Dame', 'Fighting Irish', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/87.png'),
('ncaamb_ohio_state', 'Ohio State', 'Buckeyes', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/194.png'),
('ncaamb_oklahoma', 'Oklahoma', 'Sooners', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/201.png'),
('ncaamb_oklahoma_state', 'Oklahoma State', 'Cowboys', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/197.png'),
('ncaamb_ole_miss', 'Ole Miss', 'Rebels', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/145.png'),
('ncaamb_oregon', 'Oregon', 'Ducks', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png'),
('ncaamb_oregon_state', 'Oregon State', 'Beavers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/204.png'),
('ncaamb_penn_state', 'Penn State', 'Nittany Lions', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/213.png'),
('ncaamb_pitt', 'Pittsburgh', 'Panthers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/221.png'),
('ncaamb_purdue', 'Purdue', 'Boilermakers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png'),
('ncaamb_rutgers', 'Rutgers', 'Scarlet Knights', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/164.png'),
('ncaamb_south_carolina', 'South Carolina', 'Gamecocks', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png'),
('ncaamb_southern_cal', 'USC', 'Trojans', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/30.png'),
('ncaamb_smu', 'SMU', 'Mustangs', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png'),
('ncaamb_stanford', 'Stanford', 'Cardinal', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/24.png'),
('ncaamb_syracuse', 'Syracuse', 'Orange', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/183.png'),
('ncaamb_tcu', 'TCU', 'Horned Frogs', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png'),
('ncaamb_tennessee', 'Tennessee', 'Volunteers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png'),
('ncaamb_texas', 'Texas', 'Longhorns', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/251.png'),
('ncaamb_texas_am', 'Texas A&M', 'Aggies', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/245.png'),
('ncaamb_texas_tech', 'Texas Tech', 'Red Raiders', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png'),
('ncaamb_ucla', 'UCLA', 'Bruins', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/26.png'),
('ncaamb_ucf', 'UCF', 'Knights', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png'),
('ncaamb_utah', 'Utah', 'Utes', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/254.png'),
('ncaamb_vanderbilt', 'Vanderbilt', 'Commodores', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/238.png'),
('ncaamb_virginia', 'Virginia', 'Cavaliers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/258.png'),
('ncaamb_virginia_tech', 'Virginia Tech', 'Hokies', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/259.png'),
('ncaamb_wake_forest', 'Wake Forest', 'Demon Deacons', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/154.png'),
('ncaamb_washington', 'Washington', 'Huskies', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/264.png'),
('ncaamb_washington_state', 'Washington State', 'Cougars', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/265.png'),
('ncaamb_west_virginia', 'West Virginia', 'Mountaineers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/277.png'),
('ncaamb_wisconsin', 'Wisconsin', 'Badgers', 'NCAAMB', 'basketball', 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png');