-- Add NFL Teams (32 teams)
INSERT INTO public.teams (id, name, mascot, league, sport) VALUES
('nfl_cardinals', 'Arizona Cardinals', 'Cardinals', 'NFL', 'Football'),
('nfl_falcons', 'Atlanta Falcons', 'Falcons', 'NFL', 'Football'),
('nfl_ravens', 'Baltimore Ravens', 'Ravens', 'NFL', 'Football'),
('nfl_bills', 'Buffalo Bills', 'Bills', 'NFL', 'Football'),
('nfl_panthers', 'Carolina Panthers', 'Panthers', 'NFL', 'Football'),
('nfl_bears', 'Chicago Bears', 'Bears', 'NFL', 'Football'),
('nfl_bengals', 'Cincinnati Bengals', 'Bengals', 'NFL', 'Football'),
('nfl_browns', 'Cleveland Browns', 'Browns', 'NFL', 'Football'),
('nfl_cowboys', 'Dallas Cowboys', 'Cowboys', 'NFL', 'Football'),
('nfl_broncos', 'Denver Broncos', 'Broncos', 'NFL', 'Football'),
('nfl_lions', 'Detroit Lions', 'Lions', 'NFL', 'Football'),
('nfl_packers', 'Green Bay Packers', 'Packers', 'NFL', 'Football'),
('nfl_texans', 'Houston Texans', 'Texans', 'NFL', 'Football'),
('nfl_colts', 'Indianapolis Colts', 'Colts', 'NFL', 'Football'),
('nfl_jaguars', 'Jacksonville Jaguars', 'Jaguars', 'NFL', 'Football'),
('nfl_chiefs', 'Kansas City Chiefs', 'Chiefs', 'NFL', 'Football'),
('nfl_raiders', 'Las Vegas Raiders', 'Raiders', 'NFL', 'Football'),
('nfl_chargers', 'Los Angeles Chargers', 'Chargers', 'NFL', 'Football'),
('nfl_rams', 'Los Angeles Rams', 'Rams', 'NFL', 'Football'),
('nfl_dolphins', 'Miami Dolphins', 'Dolphins', 'NFL', 'Football'),
('nfl_vikings', 'Minnesota Vikings', 'Vikings', 'NFL', 'Football'),
('nfl_patriots', 'New England Patriots', 'Patriots', 'NFL', 'Football'),
('nfl_saints', 'New Orleans Saints', 'Saints', 'NFL', 'Football'),
('nfl_giants', 'New York Giants', 'Giants', 'NFL', 'Football'),
('nfl_jets', 'New York Jets', 'Jets', 'NFL', 'Football'),
('nfl_eagles', 'Philadelphia Eagles', 'Eagles', 'NFL', 'Football'),
('nfl_steelers', 'Pittsburgh Steelers', 'Steelers', 'NFL', 'Football'),
('nfl_49ers', 'San Francisco 49ers', '49ers', 'NFL', 'Football'),
('nfl_seahawks', 'Seattle Seahawks', 'Seahawks', 'NFL', 'Football'),
('nfl_buccaneers', 'Tampa Bay Buccaneers', 'Buccaneers', 'NFL', 'Football'),
('nfl_titans', 'Tennessee Titans', 'Titans', 'NFL', 'Football'),
('nfl_commanders', 'Washington Commanders', 'Commanders', 'NFL', 'Football')
ON CONFLICT (id) DO NOTHING;

-- Add MLB Teams (30 teams)
INSERT INTO public.teams (id, name, mascot, league, sport) VALUES
('mlb_diamondbacks', 'Arizona Diamondbacks', 'Diamondbacks', 'MLB', 'Baseball'),
('mlb_braves', 'Atlanta Braves', 'Braves', 'MLB', 'Baseball'),
('mlb_orioles', 'Baltimore Orioles', 'Orioles', 'MLB', 'Baseball'),
('mlb_redsox', 'Boston Red Sox', 'Red Sox', 'MLB', 'Baseball'),
('mlb_whitesox', 'Chicago White Sox', 'White Sox', 'MLB', 'Baseball'),
('mlb_cubs', 'Chicago Cubs', 'Cubs', 'MLB', 'Baseball'),
('mlb_reds', 'Cincinnati Reds', 'Reds', 'MLB', 'Baseball'),
('mlb_guardians', 'Cleveland Guardians', 'Guardians', 'MLB', 'Baseball'),
('mlb_rockies', 'Colorado Rockies', 'Rockies', 'MLB', 'Baseball'),
('mlb_tigers', 'Detroit Tigers', 'Tigers', 'MLB', 'Baseball'),
('mlb_astros', 'Houston Astros', 'Astros', 'MLB', 'Baseball'),
('mlb_royals', 'Kansas City Royals', 'Royals', 'MLB', 'Baseball'),
('mlb_angels', 'Los Angeles Angels', 'Angels', 'MLB', 'Baseball'),
('mlb_dodgers', 'Los Angeles Dodgers', 'Dodgers', 'MLB', 'Baseball'),
('mlb_marlins', 'Miami Marlins', 'Marlins', 'MLB', 'Baseball'),
('mlb_brewers', 'Milwaukee Brewers', 'Brewers', 'MLB', 'Baseball'),
('mlb_twins', 'Minnesota Twins', 'Twins', 'MLB', 'Baseball'),
('mlb_mets', 'New York Mets', 'Mets', 'MLB', 'Baseball'),
('mlb_yankees', 'New York Yankees', 'Yankees', 'MLB', 'Baseball'),
('mlb_athletics', 'Oakland Athletics', 'Athletics', 'MLB', 'Baseball'),
('mlb_phillies', 'Philadelphia Phillies', 'Phillies', 'MLB', 'Baseball'),
('mlb_pirates', 'Pittsburgh Pirates', 'Pirates', 'MLB', 'Baseball'),
('mlb_padres', 'San Diego Padres', 'Padres', 'MLB', 'Baseball'),
('mlb_giants', 'San Francisco Giants', 'Giants', 'MLB', 'Baseball'),
('mlb_mariners', 'Seattle Mariners', 'Mariners', 'MLB', 'Baseball'),
('mlb_cardinals', 'St. Louis Cardinals', 'Cardinals', 'MLB', 'Baseball'),
('mlb_rays', 'Tampa Bay Rays', 'Rays', 'MLB', 'Baseball'),
('mlb_rangers', 'Texas Rangers', 'Rangers', 'MLB', 'Baseball'),
('mlb_bluejays', 'Toronto Blue Jays', 'Blue Jays', 'MLB', 'Baseball'),
('mlb_nationals', 'Washington Nationals', 'Nationals', 'MLB', 'Baseball')
ON CONFLICT (id) DO NOTHING;

-- Add NCAAF Teams (Major Conference Teams - 70 teams across major conferences)
INSERT INTO public.teams (id, name, mascot, league, sport) VALUES
-- SEC Teams
('ncaaf_alabama', 'Alabama', 'Crimson Tide', 'NCAAF', 'Football'),
('ncaaf_arkansas', 'Arkansas', 'Razorbacks', 'NCAAF', 'Football'),
('ncaaf_auburn', 'Auburn', 'Tigers', 'NCAAF', 'Football'),
('ncaaf_florida', 'Florida', 'Gators', 'NCAAF', 'Football'),
('ncaaf_georgia', 'Georgia', 'Bulldogs', 'NCAAF', 'Football'),
('ncaaf_kentucky', 'Kentucky', 'Wildcats', 'NCAAF', 'Football'),
('ncaaf_lsu', 'LSU', 'Tigers', 'NCAAF', 'Football'),
('ncaaf_ole_miss', 'Ole Miss', 'Rebels', 'NCAAF', 'Football'),
('ncaaf_mississippi_state', 'Mississippi State', 'Bulldogs', 'NCAAF', 'Football'),
('ncaaf_missouri', 'Missouri', 'Tigers', 'NCAAF', 'Football'),
('ncaaf_south_carolina', 'South Carolina', 'Gamecocks', 'NCAAF', 'Football'),
('ncaaf_tennessee', 'Tennessee', 'Volunteers', 'NCAAF', 'Football'),
('ncaaf_texas_am', 'Texas A&M', 'Aggies', 'NCAAF', 'Football'),
('ncaaf_vanderbilt', 'Vanderbilt', 'Commodores', 'NCAAF', 'Football'),
('ncaaf_texas', 'Texas', 'Longhorns', 'NCAAF', 'Football'),
('ncaaf_oklahoma', 'Oklahoma', 'Sooners', 'NCAAF', 'Football'),

-- Big Ten Teams
('ncaaf_illinois', 'Illinois', 'Fighting Illini', 'NCAAF', 'Football'),
('ncaaf_indiana', 'Indiana', 'Hoosiers', 'NCAAF', 'Football'),
('ncaaf_iowa', 'Iowa', 'Hawkeyes', 'NCAAF', 'Football'),
('ncaaf_maryland', 'Maryland', 'Terrapins', 'NCAAF', 'Football'),
('ncaaf_michigan', 'Michigan', 'Wolverines', 'NCAAF', 'Football'),
('ncaaf_michigan_state', 'Michigan State', 'Spartans', 'NCAAF', 'Football'),
('ncaaf_minnesota', 'Minnesota', 'Golden Gophers', 'NCAAF', 'Football'),
('ncaaf_nebraska', 'Nebraska', 'Cornhuskers', 'NCAAF', 'Football'),
('ncaaf_northwestern', 'Northwestern', 'Wildcats', 'NCAAF', 'Football'),
('ncaaf_ohio_state', 'Ohio State', 'Buckeyes', 'NCAAF', 'Football'),
('ncaaf_penn_state', 'Penn State', 'Nittany Lions', 'NCAAF', 'Football'),
('ncaaf_purdue', 'Purdue', 'Boilermakers', 'NCAAF', 'Football'),
('ncaaf_rutgers', 'Rutgers', 'Scarlet Knights', 'NCAAF', 'Football'),
('ncaaf_wisconsin', 'Wisconsin', 'Badgers', 'NCAAF', 'Football'),
('ncaaf_ucla', 'UCLA', 'Bruins', 'NCAAF', 'Football'),
('ncaaf_usc', 'USC', 'Trojans', 'NCAAF', 'Football'),
('ncaaf_oregon', 'Oregon', 'Ducks', 'NCAAF', 'Football'),
('ncaaf_washington', 'Washington', 'Huskies', 'NCAAF', 'Football'),

-- ACC Teams
('ncaaf_boston_college', 'Boston College', 'Eagles', 'NCAAF', 'Football'),
('ncaaf_clemson', 'Clemson', 'Tigers', 'NCAAF', 'Football'),
('ncaaf_duke', 'Duke', 'Blue Devils', 'NCAAF', 'Football'),
('ncaaf_florida_state', 'Florida State', 'Seminoles', 'NCAAF', 'Football'),
('ncaaf_georgia_tech', 'Georgia Tech', 'Yellow Jackets', 'NCAAF', 'Football'),
('ncaaf_louisville', 'Louisville', 'Cardinals', 'NCAAF', 'Football'),
('ncaaf_miami', 'Miami', 'Hurricanes', 'NCAAF', 'Football'),
('ncaaf_nc_state', 'NC State', 'Wolfpack', 'NCAAF', 'Football'),
('ncaaf_north_carolina', 'North Carolina', 'Tar Heels', 'NCAAF', 'Football'),
('ncaaf_notre_dame', 'Notre Dame', 'Fighting Irish', 'NCAAF', 'Football'),
('ncaaf_pittsburgh', 'Pittsburgh', 'Panthers', 'NCAAF', 'Football'),
('ncaaf_syracuse', 'Syracuse', 'Orange', 'NCAAF', 'Football'),
('ncaaf_virginia', 'Virginia', 'Cavaliers', 'NCAAF', 'Football'),
('ncaaf_virginia_tech', 'Virginia Tech', 'Hokies', 'NCAAF', 'Football'),
('ncaaf_wake_forest', 'Wake Forest', 'Demon Deacons', 'NCAAF', 'Football'),

-- Big 12 Teams
('ncaaf_baylor', 'Baylor', 'Bears', 'NCAAF', 'Football'),
('ncaaf_byu', 'BYU', 'Cougars', 'NCAAF', 'Football'),
('ncaaf_cincinnati', 'Cincinnati', 'Bearcats', 'NCAAF', 'Football'),
('ncaaf_houston', 'Houston', 'Cougars', 'NCAAF', 'Football'),
('ncaaf_iowa_state', 'Iowa State', 'Cyclones', 'NCAAF', 'Football'),
('ncaaf_kansas', 'Kansas', 'Jayhawks', 'NCAAF', 'Football'),
('ncaaf_kansas_state', 'Kansas State', 'Wildcats', 'NCAAF', 'Football'),
('ncaaf_oklahoma_state', 'Oklahoma State', 'Cowboys', 'NCAAF', 'Football'),
('ncaaf_tcu', 'TCU', 'Horned Frogs', 'NCAAF', 'Football'),
('ncaaf_texas_tech', 'Texas Tech', 'Red Raiders', 'NCAAF', 'Football'),
('ncaaf_ucf', 'UCF', 'Knights', 'NCAAF', 'Football'),
('ncaaf_west_virginia', 'West Virginia', 'Mountaineers', 'NCAAF', 'Football'),

-- Pac-12 / Other Major Programs
('ncaaf_arizona', 'Arizona', 'Wildcats', 'NCAAF', 'Football'),
('ncaaf_arizona_state', 'Arizona State', 'Sun Devils', 'NCAAF', 'Football'),
('ncaaf_california', 'California', 'Golden Bears', 'NCAAF', 'Football'),
('ncaaf_colorado', 'Colorado', 'Buffaloes', 'NCAAF', 'Football'),
('ncaaf_stanford', 'Stanford', 'Cardinal', 'NCAAF', 'Football'),
('ncaaf_utah', 'Utah', 'Utes', 'NCAAF', 'Football'),
('ncaaf_washington_state', 'Washington State', 'Cougars', 'NCAAF', 'Football')
ON CONFLICT (id) DO NOTHING;